#定义一个对象
#tb_user:
#  name: Bonnie
#  age: 22
#  gender: 女

#定义数组/List/Set集合
#hobby:
#  - Java
#  - Game
#  - Sport

#冒号:后面 必须跟空格，作为分隔符
#层级依靠空格缩进；禁止直接按 Tab，只能用空格 （IDEA 设置：会自动把 Tab 转换成空格，规避报错）
#同层级配置左侧对齐，空格数量不硬性规定，对齐即可
#在yml格式的配置文件中，如果配置项的值是以0开头的，值需要使用''引起来，因为以0开头在yml中表示 8进制的数据。

spring:
  application:
    name: springboot-mybatis-quickstart

  #数据库的连接信息
  #使用前，请自行修改数据库url、用户名、密码信息
  datasource:
    url: jdbc:mysql://localhost:3306/[你的库名]]?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: [你的用户名]
    password: [你的密码]

#Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
